---
# APM Tracing Service
version: '3'
services:
  tracing-jaeger-agent:
    image: jaegertracing/jaeger-agent:latest
    command: [
      "/go/bin/agent-linux",
      "--collector.host-port=tracing-jaeger-collector:14267"]
    ports:
      - 6831:6831/udp
    depends_on:
      - tracing-jaeger-collector
  tracing-jaeger-collector:
    image: jaegertracing/jaeger-collector:latest
    command: [
      "/go/bin/collector-linux",
      "--span-storage.type=elasticsearch",
      "--dependency-storage.data-frequency=1m0s",
      "--es.server-urls=http://tracing-elasticsearch:9200"]
    depends_on:
      - tracing-elasticsearch
  tracing-jaeger-query:
    build: tracing/jaeger-query
    command: [
      "/go/bin/query-linux",
      "--es.server-urls=http://tracing-elasticsearch:9200",
      "--span-storage.type=elasticsearch",
      "--dependency-storage.data-frequency=1m0s",
      "--query.static-files=/go/src/jaeger-ui-build/build/"]
    ports:
      - 16686:16686
    depends_on:
      - tracing-elasticsearch
  tracing-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  tracing-dependencies:
    image: jaegertracing/spark-dependencies:latest
    environment:
      - STORAGE=elasticsearch
      - ES_NODES=http://tracing-elasticsearch:9200