version: '3.1'
services:
  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091
  prometheus:
    build: metrics/prometheus
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000