version: '3'
services:
  hello-world-client:
    build: hello-world-client
    ports:
      - 8080
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
  hello-world-service:
    build: hello-world-service
    ports:
      - 8080
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
  hello-translation-service:
    build: hello-translation-service
    ports:
      - 8080
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access