---
version: '3'
services:
  tweets-service:
    build: tweets-service-ver1
    ports:
      - 18080:8080
      - 18081:8081
  tweets-db:
    build: tweets-service-ver1-db
    environment:
      POSTGRES_PASSWORD: example
